name: Issue Commenting

on: 
    issues:
        types: [opened]

jobs:
    issue_comment:
        runs-on: ubuntu-latest
        steps:
            - name: GET Github context
              run: echo '${{ toJson(github.event) }}' | jq
              shell: bash
            - name: Creating comment
              uses: peter-evans/create-or-update-comment@v1
              with: 
                issue-number: ${{ github.event.issue.number }}
                body: |
                  Thanks for opening this issue! Please check out our contributing guidelines ^^.
                reaction: +1