name: Triggered Rebase

on:
  push:
    branches: [ development ]

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Rebase development into main
      run: |
        git checkout development
        git pull origin development
        git checkout main
        git rebase development
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push rebased main branch
      run: |
        git push origin main -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}