name: Triggered Merge No Fast Forward

on:
  push:
    branches: [ dev ]

jobs:
  MergeBranches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Merge development into main
      run: |
        git config --global user.email withbimatara@gmail.com
        git config --global user.name Haalloobim
        git checkout dev
        git pull origin dev
        git checkout main
        git merge --no-ff --no-edit dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push merged main branch
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}