name: Triggered Rebase

on:
  push:
    branches: [ dev ]

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Rebase development into main
      run: |
        git checkout dev
        git pull origin dev
        git checkout main
        git rebase dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push rebased main branch
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}