name: Testing Workflows
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs: 
  JobTest:
    runs-on: ubuntu-latest
    steps: 
      - name: Testing Job
        run: echo "Testing Job" 
        shell: bash